server:
  port: 19999

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redispw
    timeout: 60000